### ISSUE TITLE
Docker TODO list

### ISSUE THREAD

**Issue by shiltemann** [ErasmusMC-Bioinformatics/streeklab-haarlem#3]
- [x] Add test data
- [x] Set up quay.io triggers
- [x] Configure workflows in docker image (as published workflows, use ephemeris)
- [x] Docker compose file
- [ ] Detailed Instructions and FAQ in README
- [ ] Test workflows (ireport on hla working?)
- [ ] automated workflow testing?

ping @davidvanzessen
